apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coordinador-ingress
  namespace: blockchain
  annotations:
    kubernetes.io/ingress.global-static-ip-name: coordinador-ip
    networking.gke.io/managed-certificates: coordinador-cert
spec:
  ingressClassName: gce
  defaultBackend:
    service:
      name: coordinador
      port:
        number: 80
