apiVersion: v1
kind: ConfigMap
metadata:
  name: pool-config
  namespace: pool
data:
  HOST_URI: "http://coordinador.blockchain"
  RABBIT_HOST: "rabbitmq.pool"
  PROCESSING_TIER: "1"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  # REDIS_DB: "0"
  POOL_ID: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvj+a1jYK5LFk+ZuYWyPo
    EuKsrkvHliM541M0LDLsGO1GoPna68qDw9j8c6mwUiNLV9eUxcJUsrltcLrYfLxP
    x06CCVy50E2sI2WFgMvXbClpokjqnopsV9FkPu3NVIxEJxSbMR6LdcLyWqKXMxI6
    +XHDVHnDSWnt35Oxb9wd0TTeLAdcPf87IH53rtSkkid1mLgmqk6NNUhdW625Tq+G
    ebkZhPj0xxuohgyQ0snEV1kys2Kns11uQ/NhLNIzc6+Qfv1mM5+PYafCjFRUuKJ+
    AN/O9gCboyLIpqjYMRSur0Wr+i8zagQQoeJMtPET6m0+qw9ufRw4UaESk1nCDj5G
    mwIDAQAB
    -----END PUBLIC KEY-----
