apiVersion: v1
kind: ConfigMap
metadata:
  name: pool-config
  namespace: pool
data:
  HOST_URI: "http://34.49.188.247"
  RABBIT_HOST: "104.196.112.104"
  PROCESSING_TIER: "1"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  # REDIS_DB: "0"
  POOL_ID: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvj+a1jYK5LFk+ZuYWyPo
    EuKsrkvHliM541M0LDLsGO1GoPna68qDw9j8c6mwUiNLV9eUxcJUsrltcLrYfLxP
    x06CCVy50E2sI2WFgMvXbClpokjqnopsV9FkPu3NVIxEJxSbMR6LdcLyWqKXMxI6
    +XHDVHnDSWnt35Oxb9wd0TTeLAdcPf87IH53rtSkkid1mLgmqk6NNUhdW625Tq+G
    ebkZhPj0xxuohgyQ0snEV1kys2Kns11uQ/NhLNIzc6+Qfv1mM5+PYafCjFRUuKJ+
    AN/O9gCboyLIpqjYMRSur0Wr+i8zagQQoeJMtPET6m0+qw9ufRw4UaESk1nCDj5G
    mwIDAQAB
    -----END PUBLIC KEY-----
  POOL_PK: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC+P5rWNgrksWT5
    m5hbI+gS4qyuS8eWIznjUzQsMuwY7Uag+drryoPD2PxzqbBSI0tX15TFwlSyuW1w
    uth8vE/HToIJXLnQTawjZYWAy9dsKWmiSOqeimxX0WQ+7c1UjEQnFJsxHot1wvJa
    opczEjr5ccNUecNJae3fk7Fv3B3RNN4sB1w9/zsgfneu1KSSJ3WYuCaqTo01SF1b
    rblOr4Z5uRmE+PTHG6iGDJDSycRXWTKzYqezXW5D82Es0jNzr5B+/WYzn49hp8KM
    VFS4on4A3872AJujIsimqNgxFK6vRav6LzNqBBCh4ky08RPqbT6rD259HDhRoRKT
    WcIOPkabAgMBAAECggEAHZjAik2rASv1xP0nRRp/apy393+Tg7BkO5DAn5WmdDRJ
    lhZ4r9D4EbpKf+Xop8aU3IwNuXxDd/Bv7acrsbAMCzoT8cfqolTLEFClZcWQdGO2
    6sfENDjdpQXOvhl5pYsSuS+z+v7A/GeBE4eS1R+jbBX+KMCumFex6WPNKVVJkDeQ
    AwbEqgCe9aBp0FKK1iEkolW5oCRuy7JVfMkqJf9ifEUc/ANg23HW1a0R5JwzPgvc
    yL2BcEk6U5k/dzIj7VLzkHL9XC8/SEyMYNEpUVw0zFVVLO8/Yi/gNEJWOVwppSAo
    aKMQqxQaMNbz2YHRiKCnfVX63b2cjPIItPl/8Gr+uQKBgQDqsXCJL5f6tZRjAnDB
    hxdBJ9PaChwdT7jRIt75CogyWj2dFZ68EPMi9qvY71GA6pQtpqKyBdOYtuZrHTQ4
    v25n5D+7vIPvWBkNwvAaWbBaCQc3ztmfurXrE53buPDAXD71OMZn7K0en8cFiqDR
    vrxKMLQns3DLjo2kkCm3MvW2iQKBgQDPhTdBHYMJK95bNier1iV3NOjew5/gcfFK
    /EQGWrAvr45WLZUhej41f9ADQvhPnyk1mH/6JwzAExGUY1DQ34uypPJGNnY4PC6C
    O5ylEk/uf05z0VTM1677BiRfN/BumXzDd0NGMbqydWEAUihPEMg3NKeHH9UF+fZZ
    fEvaWQtLAwKBgAxazuvJ35xJFsinhjwJ2oWJjTN7OMOqQLZxuX8uuMC902SDkNmh
    ossCZUWEQ6wfrTFCBmqMt/jgF/0nimo6WZuKfnhpkiB1aMw6qN0aP5hdxU2AzCAG
    ejEn1TWN5M6bjIzoMjmiUfK8woNeKt0fx1W4fqNgZN2yYW56UFfejOTRAoGAWICp
    9f1OGyU4aZIJDUIBLHvGLOslTiWKEL7RjBw1M8EdZSd/iI2H5m0iG6H+IIbynkbx
    nY/14hy/zJcmqk4MWB38rXEgrg8MjsI5pjTPHhnxLXfDQLFjkO8np+xFgAW5res5
    J8ChrOZefjKLulyf5ttv7zLmOOxH4hYei3qaVF0CgYBzt6Qep7ium4+ACGyPPqOQ
    TRTh6E9XdDwY9B6N9OQRs08foM6TuPkfIiqxgo78mvq/a/dKnnNswtvc+1euhNhe
    Ng5WVvoKves4M0nQ0HhQdfaa7BeKIdz1+thgYL5vB/FRd6a6a7JTI8uDKse90yIY
    1Q22FaAn5711MNsV3i0/bw==
    -----END PRIVATE KEY-----