apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pool-ingress
  namespace: pool
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - pool.34.23.224.114.nip.io
      secretName: pool-tls
  rules:
    - host: pool.34.23.224.114.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pool
                port:
                  number: 80