##########################################
# CONFIGMAP: Definitions (colas + exchange)
##########################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-definitions
  namespace: pool
data:
  definitions.json: |
    {
      "users": [
        {
          "name": "blockchain",
          "password": "blockchain123",
          "tags": "administrator"
        }
      ],
      "vhosts": [
        { "name": "/" }
      ],
      "permissions": [
        {
          "user": "blockchain",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ],
      "exchanges": [
        {
          "name": "blockchain.exchange",
          "vhost": "/",
          "type": "fanout",
          "durable": true
        }
      ],
      "queues": [],
      "bindings": []
    }


---
##########################################
# SERVICE HEADLESS (Requerido por StatefulSet)
##########################################
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: pool
spec:
  clusterIP: None
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      name: amqp
    - port: 15672
      name: http

---
##########################################
# SERVICE EXTERNO (LoadBalancer)
##########################################
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-external
  namespace: pool
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: http
      port: 15672
      targetPort: 15672

---
##########################################
# STATEFULSET â€” RabbitMQ
##########################################
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: pool
spec:
  serviceName: rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      nodeSelector:
          role: infraestructura
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management

          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: http

          ############################
          # VARIABLES DE ENTORNO
          ############################
          env:
            - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
              value: "-rabbitmq_management load_definitions \"/etc/rabbitmq/definitions.json\""

          ############################
          # PROBES
          ############################
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "ping"]
            initialDelaySeconds: 60
            timeoutSeconds: 10

          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "check_port_connectivity"]
            initialDelaySeconds: 60
            timeoutSeconds: 10

          ############################
          # RECURSOS
          ############################
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          ############################
          # VOLUMES
          ############################
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq

            - name: rabbitmq-definitions
              mountPath: /etc/rabbitmq/definitions.json
              subPath: definitions.json

      volumes:
        - name: rabbitmq-definitions
          configMap:
            name: rabbitmq-definitions

  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
