apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pool-ingress
  namespace: pool
  annotations:
    kubernetes.io/ingress.global-static-ip-name: pool-ip
    networking.gke.io/managed-certificates: pool-cert
spec:
  ingressClassName: gce
  rules:
  - host: pool.blockchain-sd.publicvm.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pool
            port:
              number: 80