apiVersion: apps/v1
kind: Deployment
metadata:
  name: pool
  namespace: pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pool
  template:
    metadata:
      labels:
        app: pool
    spec:
      containers:
        - name: pool
          image: matiasherrneder/blockchain-pool:0a6c223
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: pool-config
      nodeSelector:
        role: infraestructura
---
apiVersion: v1
kind: Service
metadata:
  name: pool
  namespace: pool
spec:
  selector:
    app: pool
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer
