apiVersion: v1
kind: Namespace
metadata:
  name: secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: secret
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: secret
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
