# apiVersion: keda.sh/v1alpha1
# kind: ScaledObject
# metadata:
#   name: minero-difficulty
#   namespace: blockchain
# spec:
#   scaleTargetRef:
#     name: minero
#   minReplicaCount: 1
#   maxReplicaCount: 5
#   pollingInterval: 15
#   cooldownPeriod: 60
#   triggers:
#     - type: prometheus
#       metadata:
#         serverAddress: http://prometheus-server.observability.svc.cluster.local
#         metricName: mining_workers_desired
#         query: mining_workers_desired
#         threshold: "1"
