name: Coordinador Pipeline

on:
  push:
    branches:
      - dev
    paths:
      - TPs/TP5/Pilar2/coordinador/**

env:
  IMAGE_NAME: matiasherrneder/blockchain-coordinador

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Image Tag
        id: vars
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME:${{ steps.vars.outputs.TAG }} ./TPs/TP5/Pilar2/coordinador/
          docker push $IMAGE_NAME:${{ steps.vars.outputs.TAG }}

      - name: Update Kubernetes Manifests
        run: |
          sed -i "s|image: .*|image: $IMAGE_NAME:${{ steps.vars.outputs.TAG }}|" TPs/TP5/Pilar2/infra/manifests/coordinador/coordinador.yaml
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add TPs/TP5/Pilar2/infra/manifests/coordinador/coordinador.yaml
          git commit -m "Update image to $IMAGE_NAME:${{ steps.vars.outputs.TAG }}" || echo "No changes to commit"

          git pull --rebase origin dev
          git push origin dev