name: Mineros Pipeline

on:
  push:
    branches:
      - dev
    paths:
      - TPs/TP5/Pilar2/mineros/mineroCPU/**

env:
  IMAGE_CPU: matiasherrneder/blockchain-minero
  IMAGE_GPU: matiasherrneder/blockchain-minero-gpu

jobs:

  # ---------------------------
  #  CPU
  # ---------------------------
  build-cpu:
    runs-on: ubuntu-latest
    environment: secrets

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Image Tag
        id: vars
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push CPU Image
        run: |
          docker build -t $IMAGE_CPU:${{ steps.vars.outputs.TAG }} ./TPs/TP5/Pilar2/mineros/mineroCPU/
          docker push $IMAGE_CPU:${{ steps.vars.outputs.TAG }}

      - name: Update CPU Kubernetes Manifest
        run: |
          sed -i "s|image: .*|image: $IMAGE_CPU:${{ steps.vars.outputs.TAG }}|" TPs/TP5/Pilar2/infra/manifests/mineroCPU/mineroCPU.yaml
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add TPs/TP5/Pilar2/infra/manifests/mineroCPU/mineroCPU.yaml
          git commit -m "Update CPU image to $IMAGE_CPU:${{ steps.vars.outputs.TAG }}" || echo "No changes to commit"

          git pull --rebase origin dev
          git push origin dev

  # ---------------------------
  #  GPU
  # ---------------------------
  build-gpu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Image Tag
        id: vars
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push GPU Image
        run: |
          docker build -t $IMAGE_GPU:${{ steps.vars.outputs.TAG }} ./TPs/TP5/Pilar2/mineros/mineroCPU/
          docker push $IMAGE_GPU:${{ steps.vars.outputs.TAG }}

      - name: Update GPU Kubernetes Manifest
        run: |
          sed -i "s|image: .*|image: $IMAGE_GPU:${{ steps.vars.outputs.TAG }}|" TPs/TP5/Pilar2/infra/manifests/mineroGPU/mineroGPU.yaml
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add TPs/TP5/Pilar2/infra/manifests/mineroGPU/mineroGPU.yaml
          git commit -m "Update GPU image to $IMAGE_GPU:${{ steps.vars.outputs.TAG }}" || echo "No changes to commit"

          git pull --rebase origin dev
          git push origin dev
