apiVersion: apps/v1
kind: Deployment
metadata:
  name: minero-gpu
  namespace: blockchain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minero-gpu
  template:
    metadata:
      labels:
        app: minero-gpu
    spec:
      runtimeClassName: nvidia
      containers:
        - name: minero-gpu
          image: matiasherrneder/blockchain-minero-gpu:3902368
          resources:
            limits:
              nvidia.com/gpu: 1
          envFrom:
            - configMapRef:
                name: miner-config
#---
#apiVersion: autoscaling/v2
#kind: HorizontalPodAutoscaler
#metadata:
#  name: minero-hpa
#  namespace: blockchain
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: minero
#  minReplicas: 1
#  maxReplicas: 5
#  metrics:
#    - type: Resource
#      resource:
#        name: cpu
#        target:
#          type: Utilization
#          averageUtilization: 60
